# This file was generated by GoReleaser. DO NOT EDIT.
cask "outrider" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "9833f0f8c174b3f7782d6c811b016313b19ea783903d3bea6d4d9e8afff38e84"
      url "https://github.com/appetizers-io/outrider/releases/download/v#{version}/outrider_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d304297b90ce19266e64676fa37645ee4f1ed3d2315d3fb2231b3545e2e024de"
      url "https://github.com/appetizers-io/outrider/releases/download/v#{version}/outrider_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1814442aa09891070b9f1081a9b7717dcf38175e08cceb6f1e2a7367ea1ff641"
      url "https://github.com/appetizers-io/outrider/releases/download/v#{version}/outrider_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11badf4cb59882b7974e6be5a7597174ef626824f4bbe01be9bf4162b4672ca8"
      url "https://github.com/appetizers-io/outrider/releases/download/v#{version}/outrider_#{version}_linux_amd64.tar.gz"
    end
  end

  name "outrider"
  desc "Watches your GitHub notifications and opens a local coding agent for the PRs that need you"
  homepage "https://github.com/appetizers-io/outrider"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "outrider"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/outrider"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    outrider also needs claude (Claude Code) or codex; tmux only for the tmux launcher.
    Log in to gh first (gh auth login), then in a checkout:
      outrider doctor
      outrider --dry-run --once
      outrider config generate --write
    Docs: https://github.com/appetizers-io/outrider#readme
  EOS
end
